//Program to Demonstrate Enacapsulation
// OR
//Program to Demonstrate Class a Object

#include<iostream.h>
#include<conio.h>
class student
{
private:
				 int roll no;
				 char name[30];
public:
				 void get()
				 {
				 cout<<end1<<end<<end1<<end1;
				 cout<<"enter rollno:-">;
				 cin>>rollno;
				 cout<<"enter student name:-">;
				 cin>>name;
				 }
};
void main()
{
clrscr();
student s1,s2,s3;
s1.get();
s2.get();
s3.get();
cot<<***********OUTPUT************<<end1;
cout<<"Rollno"<<"\t"<<"name"<<"\t"<<"marks1"<<"\t"
		<<"marks2"<<"\t"<<"marks1"<<"\t"<<end1;
		cout<<"**************"<<end1;

		s1.put();
		s2.put();
		s3.put();
getch();
}


